<?php

/**
 * @file
 * Install, update and uninstall functions for the colorbox module.
 */

/**
 * Implements hook_install().
 */
function initializer_install() {
  // Make sure the theme is installed
  $theme_handler = \Drupal::service('theme_handler');
  $theme_handler->install(['seven']);

// Set it as the admin theme
  $config = \Drupal::service('config.factory')->getEditable('system.theme');
  $config->set('admin', 'seven')->save();
}
